---
title: "Investigation of Fractal Carbon Nanotube Networks for Biophilic Neural Sensing Applications "
collection: publications
permalink: /publication/CNTsensing
excerpt: 'We propose a carbon-nanotube-based neural sensor designed to exploit the electrical sensitivity of an inhomogeneous fractal network of conducting channels. This network forms the active layer of a multi-electrode field effect transistor that in future applications will be gated by the electrical potential associated with neuronal signals. Using a combination of simulated and fabricated networks, we show that thin films of randomly-arranged carbon nanotubes (CNTs) self-assemble into a network featuring statistical fractal characteristics. The extent to which the network’s non-linear responses will generate a superior detection of the neuron’s signal is expected to depend on both the CNT electrical properties and the geometric properties of the assembled network. We therefore perform exploratory experiments that use metallic gates to mimic the potentials generated by neurons. We demonstrate that the fractal scaling properties of the network, along with their intrinsic asymmetry, generate electrical signatures that depend on the potential’s location. We discuss how these properties can be exploited for future neural sensors.'
date: 2021-03-04
venue: 'Nanomaterials'
paperurl: 'https://www.mdpi.com/2079-4991/11/3/636'
---

